map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

map $request_uri $api_uri {
  ~^/api(?<rest>/.*)$ $rest;
  default $request_uri;
}

client_max_body_size 10G;

server {
  listen 8080 default_server;

  add_header X-Frame-Options "DENY";
  add_header Content-Security-Policy "frame-ancestors 'none';";

  location /v2/ {
    proxy_read_timeout 600s;
    proxy_request_buffering off;
    rewrite ^/v2/(.*)$ /v2/$1 break;
    proxy_pass http://server:3000;
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /api/ {
    proxy_read_timeout 600s;
    proxy_request_buffering off;
    proxy_pass http://server:3000$api_uri;
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /v1/graphql {
    proxy_pass http://hasura:8080/v1/graphql;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
  }

  location / {
    proxy_pass http://client:8080/;
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}